Got sort by album working and added regenerate button
Music-Visualization-MQP/mono-repo pull request #50
Opened 2024-11-01 14:49 UTC by ibixler

fixes #48 fixes #49

this pr adds a regenerate button 
as well as ranking art display by album and not song

2024-11-05 19:39 UTC, michibatoryu reviewed
Tested it out and both of the functionalities work, yay! Is the loading stuff in here for the regenerate button or sort by album functionality? Otherwise maybe we should move that onto another branch for now...

2024-11-06 04:01 UTC, notsoli requested changes
ngl this one was rough

2024-11-06 04:01 UTC, notsoli commented
Everything works fine, but i'm a little bit flabbergasted that u just overwrote the sort by song code instead of making a new function lol. No need to make an option to toggle yet, but keeping both is a must imo.

2024-11-06 04:10 UTC, notsoli requested changes

2024-11-06 04:10 UTC, notsoli commented on frontend/src/routes/(app)/+layout.svelte
Why the extra whitespace 😭

2024-11-08 00:10 UTC, notsoli approved these changes
pogger

2024-11-12 19:27 UTC, merged